### ISSUE TITLE
[Security] Reported via email

### ISSUE THREAD

**Issue by OmgImAlexis** [louislam/uptime-kuma#1328]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

This is to track the issue reported via email. Details can be shared here once the issue has been resolved.

### 👟 Reproduction steps

See email

### 👀 Expected behavior

See email

### 😓 Actual Behavior

See email

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

Demo instance

### 🌐 Browser

Google Chrome

**Comment by OmgImAlexis** [comment]
> Thanks, but currently uptime kuma is a single user application, so it is not a issue currently.

Please reopen this. This IS an issue. I can completely crash the demo instance and even use it to DOS sites. Even as a single user application this is an issue. I find it quite irresponsible to just close this.

**Comment by OmgImAlexis** [comment]
Does this mean I can share the problem on here then since you've deemed it not a security risk? I feel users have a right to know so they themselves can decide the risk factor here.

**Comment by hogcycle** [comment]
send it you wont

**Comment by OmgImAlexis** [comment]
I also noticed a few other issues, I'll send you an email about those too.

**Comment by louislam** [comment]
Yes, I think there are 3 issues, I agree that 1st and 2nd are security issues, but 3rd should be not.

1. For console.log issue, I may need some time to figure it out where is it, would be appreciated if you could email me where is it.

2. For DDOS issue, it should be fixed, but it only hurt my demo site.
https://github.com/louislam/uptime-kuma/commit/595cd9322080b209d9a7925463c850cae29d2c33

3. For input validations, I did mention that the input validations are frontend only currently. (https://github.com/louislam/uptime-kuma/issues/625#issuecomment-939344756) Admin account should not share to other users as always. 

In my point of view, since this is a single user application, it should not be a problem. I think no one will try to hack themself.

For example, you send the Windows admin account to other users and then he delete some dll files at C:\Windows and crash the Windows. It does hurt the system, but I think it is not a security issue. 

However let say Windows is having a bug that let hackers login the admin account without password and delete some dll files, that is a security issue.

Of course, I am not against this. Ultimately, I strongly agree that server side checking should be implemented. But please understand that I maintain this project with my free time only. Implementing this could be a time consuming task.

**Comment by OmgImAlexis** [comment]
This issue should be re-opened as it's not resolved. 


1. This shouldn't need me to email you the location. Search the code... 

2. Wasn't fixed at all. https://github.com/louislam/uptime-kuma/commit/595cd9322080b209d9a7925463c850cae29d2c33#r67528328

3. Good choice in using Windows as an example here as Windows actually prevents exactly this type of thing.

> For example, you send the Windows admin account to other users and then he delete some dll files at C:\Windows and crash the Windows. It does hurt the system, but I think it is not a security issue.

If I leave a windows PC unattended and then someone walks by and tries to delete something in an admin owned directory they're prompted with the UAC. With Uptime kuma if I leave a browser authenticated and walk away this just lets anyone do whatever they want. 


I'd also highly suggest you do some research into security. It's not nearly as black and white as you're making it out to be.

**Comment by OmgImAlexis** [comment]
Also this issue should never have been marked as invalid. This is a valid security issue please remove the "invalid" tag and add "security".

**Comment by louislam** [comment]
> If I leave a browser authenticated and walk away

Sorry in this case, anyone can steal all your saved passwords in Chrome. 
So Chrome is having security issue?

I re-open it for more discussion.

**Comment by louislam** [comment]
> 



> Would you please kindly stop harrassing this open source maintainer. Your entitled attitude is frankly unbearable.
> 
> Security issues are indeed inportant, however what you're forgetting is that you're not talking to some faceless gigacorp here. Instead, this is a human being who has decided to donate their time working on something for free to the world.
> 
> It is completely unacceptable to boss them around like this.

Thank you for understanding!

**Comment by Hypfer** [comment]
> I find it quite irresponsible to just close this.

> Also this issue should never have been marked as invalid.

> I feel users have a right to know so they themselves can decide the risk factor here.

> This issue should be re-opened as it's not resolved.

> This shouldn't need me to email you the location. Search the code...

Yes yes. These are all clearly neutral statements showing your support for and your willingness to work with the maintainer.

**Comment by OmgImAlexis** [comment]
> > @louislam did you not see this comment? I’ll be releasing the details publicly 90 days after the first email as I feel this should be disclosed to users. I believe a CVE should also be issued for this.
> 
> This is also clearly not in any way pressuring the maintainer.

What in the world are you on about? Have you not heard of responsible disclure? This is standard practise.

**Comment by OmgImAlexis** [comment]
> That however is not the case. In context, it was clearly perceived as a hostile threat.

You closed the issue, I asked what was meant to be happening and stated my intention to release a CVE. What part of that is hostile?

**Comment by Hypfer** [comment]
> You closed the issue

I'm not the maintainer. I'm just _some_ maintainer tired of seeing this attitude happen on a regular basis.

> Obviously I should have just ignored it and left the repo alone.

Obviously you should've actually tried to help solving the problem if you actually care about that and not just want a CVE with your name on it.

> This shouldn't need me to email you the location. Search the code...

^ This is not how people work together on solving an issue.

**Comment by OmgImAlexis** [comment]
> I'm not the maintainer. I'm just some maintainer tired of seeing this attitude happen on a regular basis.

You get I'm **ALSO** a open source maintainer? I get abuse on a daily basis. If someone opened an issue like this(I've had plenty over the years) I would have worked with them not closed it.

> if you actually care about that and not just want a CVE with your name on it.
I honestly couldn't give two shits about the CVE number. I **DO** care about seeing projects like this used by 1000s while there are security issues. 9/10 they're there simply because no one thought to try and break the app. Looks at all the things that've been found with libraries just over the last year.

> ^ This is not how people work together on solving an issue.

Come on... this is just trying to find something to backup your point.
It was 3AM when I was replying to this, maybe I could have been a little nicer but really no one should need to point out where a console.log is. Open your editor CTRL+F "console.log" oh there it is... you know like how I did...

**Comment by OmgImAlexis** [comment]
Just to make the point obvious. Someone being blunt and stating facts is not the same as someone being hostile.

**Comment by louislam** [comment]
Thank you all, I think everyone here are trying to help the project.

I am definitely not a security expert here. I always just use my sense and experience to develop something.

Discussions and opinions are welcome. If my knowledge is not correct, feel free to correct me. Also pull requests are welcome too.

**Comment by OmgImAlexis** [comment]
@louislam is that case am I okay to open some PRs this week to add validation and other security fixes? I haven't had a chance to fully audit this app and only had a few glances at the code.

**Comment by louislam** [comment]
> @louislam in that case am I okay to open some PRs this week to add validation and other security fixes? I haven't had a chance to fully audit this app and only had a few glances at the code.

I try my best, since I am a bit lazy recently lol. 50+ pull requests are in the queue.

**Comment by CommanderStorm** [comment]
> In that case would a few small focused PRs be better to open than a single big one?

Please open PRs that are as small as they need to be to achieve the goal.
I.e. multiple PRs, but each with only one distinct addressed issue.
=> This way they stay reviewable + effective.

**Comment by CommanderStorm** [comment]
@OmgImAlexis Can this issue be closed?
