### ISSUE TITLE
1.13.0-beta.0 - status page empty

### ISSUE THREAD

**Issue by R0GGER** [louislam/uptime-kuma#1399]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When you create 2 or more status pages only one is saved by Uptime Kuma.

### 👟 Reproduction steps

1. Create status page-1 and fill it with a few monitors and click save.
2. Create status page-2 and fill it with a few monitors and click save.
3. Go back to your dashboard and open page-1 
4. Result: page-1 = empty.

### 👀 Expected behavior

Both pages should have monitors.

### 😓 Actual Behavior

...

### 🐻 Uptime-Kuma Version

1.13.0-beta.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker version 20.10.13

**Comment by louislam** [comment]
Thanks for testing it. It did happen to me, I thought I removed all monitors incidentally by hand.

**Comment by R0GGER** [comment]
@louislam Thanks!  Problem solved in 1.13.0-beta.1 after fix https://github.com/louislam/uptime-kuma/issues/1399

**Comment by R0GGER** [comment]
@rihards-simanovics 
Your status page url looks incorrect. I think because the 1.13.0-beta.* uses a new status-page url format `/status/[title]` the old one `/status` doesn't work anymore. 

Try: https://[uptime.your-domain]/status/default

**Comment by rihards-simanovics** [comment]
Hi, @R0GGER thank's for the help I'm I'm afraid there is probably something else that I am missing. I tried reinstalling using fresh `git fetch --all`, then `git checkout 1.13.0-beta.1 --force`, removed `node_modules`, then `npm i` and then tried `npm ci --development`, then `npm run download-dist` but to no avail...

Still get blank page for `/status/` and for `/status/default/` I get white page during day time and the black page (both are blank) during the night (I guess the conditional theme).

I do, though, get one error in the console (when on /status/default/). The site is behind Cloudflare, but until now (which is about eight months by now), Cloudflare did not interfere with the correct operation of the site.
![image](https://user-images.githubusercontent.com/52106095/159374737-0c43a531-ca0c-43bd-97c6-5845db2e3f99.png)

**Comment by louislam** [comment]
@rihards-simanovics

Since the beta approach is a bit new, I think it is bugged for non-Docker user.

If you want to try, you could download [dist.tar.gz](https://github.com/louislam/uptime-kuma/releases/download/1.13.0-beta.1/dist.tar.gz) from
https://github.com/louislam/uptime-kuma/releases/tag/1.13.0-beta.1

And then untar to /opt/uptime-kuma/dist/
