### ISSUE TITLE
Get Uptime Kuma Whitelisted in Cloudflare WAF

### ISSUE THREAD

**Issue by zeroav-org** [louislam/uptime-kuma#2058]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

In relation to #1333 #2054 - made a Cloudflare ticket from work account and they actually replied.

[There exists a mechanism](https://support.cloudflare.com/hc/en-us/articles/360035387431#5KX8t3C6SObnoWs5F6YOlU) to have a bot looked at by Cloudflare and whitelisted. This would help with 503 errors coming up on https monitored endpoints. 

It is a bit of a challenge with a self-hosted service as their preferred authentication methods are ASN / IP / ACL based but they do offer a machine-learning option that might be worth applying. 

> 
This allowlist is large based on reverse DNS verification, meaning that the IPs we allow really match the requesting service. In addition to this, Cloudflare uses multiple validation methods including ASN blocks and public lists. If none of these validation types are available for a customer, we use internal Cloudflare data and machine learning to identify legitimate IP addresses from good bots.

### ✔️ Solution

It is a long shot but have @louislam fill out the [form ](https://docs.google.com/forms/d/e/1FAIpQLSdqYNuULEypMnp4i5pROSc-uP6x65Xub9svD27mb8JChA_-XA/viewform)in the [Cloudflare KB article](https://support.cloudflare.com/hc/en-us/articles/360035387431-Cloudflare-bot-products-FAQs#h_5itGQRBabQ51RwT5cNJX8u).

### ❓ Alternatives

Disabling Bot Fighting mode on effected domains is a work-around but comes at a penalty of getting a lot of junk traffic coming in.
![Screenshot2-D](https://user-images.githubusercontent.com/84272417/189270724-9cc954e0-6cf3-45a1-896d-f83e63ce8b3e.png)

**Comment by louislam** [comment]
Thanks, it have been submitted.

![image](https://user-images.githubusercontent.com/1336778/189314268-915bc34e-e5b4-426a-9425-d889e305d5e9.png)

Btw, just sharing my experience. This suddenly reminded me, one of my Android app had this similar issue 2 years old. My app is using a http client with a custom user-agent. It makes requests to an API with Cloudflare. 

However, there were always maybe 1% users reported that the app was not working. After some investigations, it turned out that it blocked by Cloudflare's `Browser Integrity Check` and `Bot Fight Mode`. After turned off these options, no more reports.

Although it can block some bots, it also blocks small amount of good users.

**Comment by ZekXtreme** [comment]
Is It Possible to allow requests having Uptime-kuma as useragent  ?

**Comment by 2020media** [comment]
Any news on Cloudflare accepting Uptime Kuma as a recognised bot?
They have many other monitoring bots https://radar.cloudflare.com/traffic/verified-bots

Maybe if more users submitted a request to add it?

**Comment by mskian** [comment]
I am also facing this same issue because of bot mode enabled

try to add custom WAF rules but not working
so finally whitelist and allow Uptime Kuma IP

- Login to CF Dashboard
- websites > Choose a Cloudflare-enabled site that uses bot fight mode and Browser Integrity Check
- goto security > WAF > Open tools tab > add the IP address of uptime hosted server - set action allow and click add 
- Done it won't block the HTTP request from uptimekuma

**Note** Currently I use this solution to bypass the 403 bot block from CF - for more refer - https://developers.cloudflare.com/waf/
Cloudflare won't recommend this method - https://developers.cloudflare.com/waf/tools/ip-access-rules/
by this the temporary solution for now

**Comment by mskian** [comment]
they give the option to apply this IP list rule for **All websites in account**

**Comment by 7zx** [comment]
> I am also facing this same issue because of bot mode enabled
> 
> try to add custom WAF rules but not working so finally whitelist and allow Uptime Kuma IP
> 
> * Login to CF Dashboard
> * websites > Choose a Cloudflare-enabled site that uses bot fight mode and Browser Integrity Check
> * goto security > WAF > Open tools tab > add the IP address of uptime hosted server - set action allow and click add
> * Done it won't block the HTTP request from uptimekuma
> 
> **Note** Currently I use this solution to bypass the 403 bot block from CF - for more refer - https://developers.cloudflare.com/waf/ Cloudflare won't recommend this method - https://developers.cloudflare.com/waf/tools/ip-access-rules/ but this the temporary solution for now

i did that but i'm still getting the 403 error with Bot Fight Mode enabled, am doing something wrong?

![image](https://github.com/louislam/uptime-kuma/assets/83615960/dc455813-13e8-42a7-b763-bb627e0895ad)

**Comment by CommanderStorm** [comment]
Given that we filled out the [form ](https://docs.google.com/forms/d/e/1FAIpQLSdqYNuULEypMnp4i5pROSc-uP6x65Xub9svD27mb8JChA_-XA/viewform)in the [Cloudflare KB article](https://support.cloudflare.com/hc/en-us/articles/360035387431-Cloudflare-bot-products-FAQs#h_5itGQRBabQ51RwT5cNJX8u) and that there is not more we can do about this.

https://developers.cloudflare.com/waf/managed-rules/waf-exceptions/ can be used by clients to register UK as a exception
=> closing as resolved

**Comment by fnagel** [comment]
Is there any news in this topic? Still having issues to monitor sites behind Cloudflare proxy.

**Comment by CommanderStorm** [comment]
What news do you expect?

You can add an exception in the WAF if you need it.
Otherwise there has not been a response from filling out the form (Which I expected)

**Comment by fnagel** [comment]
> You can add an exception in the WAF if you need it.

No, I'm trying to monitor one of those website builder pages (Jimdo to be precise) and therefor have no access to the related Cloudflare.

> Otherwise there has not been a response from filling out the form (Which I expected)

I've hoped for better news regarding the "Cloudflare Bot Verification" form :-/

Anyway, thanks for the feedback and please keep up the great work!
