### ISSUE TITLE
"Show Clickable Link" checkbox does not update until entire dashboard is saved

### ISSUE THREAD

**Issue by BBaoVanC** [louislam/uptime-kuma#3794]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After checking the "Show Clickable Link" box in a monitor's setting dialog and closing the dialog, reopening the monitor's setting dialog shows the same box still unchecked giving the impression that the setting did not change. Only after saving aving the dashboard and returning to the monitor's setting dialog does the box stay checked.

### 👟 Reproduction steps

1. Press Edit Status Page
2. Press the settings cog on a monitor
3. Tick "Show Clickable Link" and close the dialog
4. Press settings cog of the same monitor again

### 👀 Expected behavior

The checkbox should stay checked to hint that it will be enabled after pressing save on the entire status page

### 😓 Actual Behavior

The checkbox remains unchecked and the setting seemingly didn't change

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Firefox 117.0.1

### 🐋 Docker Version

Docker 24.0.6

**Comment by Rai-Sahil** [comment]
Can I work on it? If you think it's could be good first issue.

**Comment by CommanderStorm** [comment]
You can work on this.
We don't assign people to issues ^^

See our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by Rai-Sahil** [comment]
Hi @BBaoVanC 

How do you recreate the bug? I tried the edit stats page it doesn't really show this checkbox.

**Comment by BBaoVanC** [comment]
> Hi @BBaoVanC
> 
> How do you recreate the bug? I tried the edit stats page it doesn't really show this checkbox.

I sent a picture with the steps of reproducing it in a different thread: https://github.com/louislam/uptime-kuma/issues/3795#issuecomment-1734471131. If it's not there, what version are you on?

**Comment by Rai-Sahil** [comment]
> > Hi @BBaoVanC
> > How do you recreate the bug? I tried the edit stats page it doesn't really show this checkbox.
> 
> I sent a picture with the steps of reproducing it in a different thread: [#3795 (comment)](https://github.com/louislam/uptime-kuma/issues/3795#issuecomment-1734471131). If it's not there, what version are you on?

I just cloned the repository from the main branch and I'm working on it? Why is there any other version?
This one https://github.com/louislam/uptime-kuma.git

**Comment by Rai-Sahil** [comment]
Oh @BBaoVanC 

Nevermind, found it. 
It's this right?
![Screenshot 2023-11-13 at 9 39 00 PM](https://github.com/louislam/uptime-kuma/assets/78111534/5840ea89-87f5-4dc2-a840-62f5f0c4311e)

**Comment by Rai-Sahil** [comment]
> You can work on this. We don't assign people to issues ^^
> 
> See our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

Hi @CommanderStorm 

I have made a PR. you can see from recording I included in the PR that the issue is fixed. All the tests from auto-check to ESLint. Everything is good.
![Screenshot 2023-11-13 at 11 38 46 PM](https://github.com/louislam/uptime-kuma/assets/78111534/f6882d51-8e6e-4a7e-879a-830973b020ca)

I was wondering if you can merge that. Would be really helpful thanks.

**Comment by CommanderStorm** [comment]
@Rai-Sahil 
Please adress the comment from nelson in the PR.

As I wrote to you via email (sending messages via multiple channels at the same time is not good practice, as it just annoys people ^^):

> I am not fully convinced that saving a single value to local storage fixes the issue as this means that
- either all checkboxes are set or not
- or maybe even requires a reload of the page to get somewhere

**Comment by Rai-Sahil** [comment]
@CommanderStorm 

If you want I can change it from the local storage to something else. From the code, I saw that you guys are saving the current state of checkbox in a variable. Even I'm doing the same thing but just storing the value in local storage. 

Although I tried refreshing the page, I saw no checkbox other than the intended one was checked or not. But I get your point that should be saved in user state. Not that if user closed the browser and re-opens it there. If you want I can come up with some other way as well.

**Comment by kevinmatthe** [comment]
It seems that this issue is still unfixed, was there a temporary solution to make it take effect?

**Comment by CommanderStorm** [comment]
> was there a temporary solution to make it take effect?

Once the entire dashboard is saved, the checkbox updates.
If you'd like to contribute a fix for this, here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md).

**Comment by BxtGeek** [comment]
looks like issue is still unfixed but also temporary solution is not working

**Comment by sanjogbhalla16** [comment]
I would like to work upon this if its still open , thank you.

**Comment by CommanderStorm** [comment]
Shure, go ahead 👍

**Comment by R-HNF** [comment]
I'll try this issue 👍

**Comment by R-HNF** [comment]
@CommanderStorm 
I have submitted PR #5250. Cloud you review it. Thank you!

**Comment by ComposeVisuaEditorDev** [comment]
can this PR be reviewed? quite an annoying problem

**Comment by fabiosimone** [comment]
The issue persists; when I check the box, it automatically unchecks itself. 

help pls

**Comment by lucayunxiao** [comment]
When I check the box, close it, it will uncheck itself.

https://github.com/user-attachments/assets/80e30b26-edb7-4f74-bbaa-02368dcd6b47

**Comment by Vilasamuni** [comment]
My system is affected too

**Comment by R-HNF** [comment]
After checking it again personally, the following change enables the `url` of `monitor` to be passed from ` PublicGroupList` to `MonitorSettingDialog`.
* https://github.com/louislam/uptime-kuma/pull/5435/files#diff-dd77c8fee76d0c064efcdec09601d58449932d86e8c6b665fb1d7cf291ad5ef6R91

As a result, the evaluation of `showLink` below seems to be working correctly, and the issue appears to be resolved.
* https://github.com/louislam/uptime-kuma/blob/5f650aef58fb97cfee1106e44802cc8ff7fcb65d/src/components/MonitorSettingDialog.vue#L122

So, I will close my PR:
* https://github.com/louislam/uptime-kuma/pull/5250

**Comment by CommanderStorm** [comment]
> the issue appears to be resolved

Thanks for investigating 🎉

**Comment by zhangpinzheng** [comment]
thanks
