### ISSUE TITLE
Prometheus: Adding new tags causes 'Added label is not included in initial labelset' error

### ISSUE THREAD

**Issue by iotux** [louislam/uptime-kuma#6470]
### 📑 I have found these related issues/pull requests

None. A search for "Prometheus" and "label" in open and closed issues did not reveal any related reports.

**Here are the diffs for proposed changes:**

**server/prometheus.js**

```
    1 --- a/server/prometheus.js
    2 +++ b/server/prometheus.js
    3 @@ -28,6 +28,7 @@
    4       * @returns {Promise<void>}
    5       */
    6      static async init() {
    7 +        PrometheusClient.register.clear();
    8          // Add all available tags as possible labels,
    9          // and use Set to remove possible duplicates (for when multiple tags contain non-ascii characters, and thus are 
      sanitized to the same label)
   10          const tags = new Set((await R.findAll("tag")).map((tag) => {
```

**server/server.js**
```
    1 --- a/server/server.js
    2 +++ b/server/server.js
    3 @@ -1214,6 +1214,8 @@
    4                  bean.color = tag.color;
    5                  await R.store(bean);
    6  
    7 +                await Prometheus.init();
    8 +
    9                  callback({
   10                      ok: true,
   11                      tag: await bean.toJSON(),
```

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

When adding a new tag to a monitor, Prometheus throws an Error: Added label "X" is not included in initial labelset for every subsequent heartbeat of that monitor. This is because the Prometheus metrics are initialized with a fixed set of labels (including all existing tags) at application startup. When a new tag is created and assigned to a monitor, it's not part of this initial label set, causing the prom-client library to throw an error when the monitor's metrics are updated.

The current workaround is to restart the Uptime Kuma server after adding a new tag, which is not ideal.

### 👟 Reproduction steps

1. Start the Uptime Kuma server.
2. Navigate to the dashboard and create any type of monitor.
3. Go to the monitor's edit page.
4. In the "Tags" section, add a new tag (e.g., server) and save the monitor.
5. Observe the application logs. You will see the Prometheus error for every heartbeat of that monitor.

### 👀 Expected behavior

The application should not throw any errors after adding a new tag. The new tag should be dynamically added to the Prometheus metrics as a label without requiring a server restart.

### 😓 Actual Behavior

The application throws an Error: Added label "X" is not included in initial labelset in the logs for every heartbeat of a monitor after a new tag has been added to it. The error persists until the server is restarted.

### 🐻 Uptime-Kuma Version

2.0.2

### 💻 Operating System and Arch

Kubuntu desktop (Ubuntu 25.10

### 🌐 Browser

Firefox 145.0.2 (64-bit)

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Node.js: Version `23.11.1` (LTS: Yes/No)

- **Database**:
  - SQLite: Embedded
- **Database Storage**:
  - **Filesystem**:
    - Linux: ext4
  - **Storage Medium**: NVMe
- **Uptime Kuma Setup**:
  - Number of monitors: `1`

### 📝 Relevant log output

```bash session
2025-12-09T11:13:39+01:00 [MONITOR] INFO: Get Monitor: 1 User ID: 1
  2025-12-09T11:13:49+01:00 [MANAGE] INFO: Resume Monitor: 1 User ID: 1
  2025-12-09T11:13:49+01:00 [MONITOR] DEBUG: [Mosquitto] Check isImportant
  2025-12-09T11:13:49+01:00 [MONITOR] DEBUG: Monitor #1 'Mosquitto': Successful Response: 7 ms | Interval: 60 seconds | Type:
  local-service
  2025-12-09T11:13:49+01:00 [UPTIME-CALC] DEBUG: Remove old data
  2025-12-09T11:13:49+01:00 [MONITOR] INFO: Get Monitor: 1 User ID: 1
  2025-12-09T11:13:49+01:00 [MONITOR] DEBUG: [Mosquitto] Send to socket
  2025-12-09T11:13:49+01:00 [MONITOR] DEBUG: [Mosquitto] Store
  2025-12-09T11:13:49+01:00 [MONITOR] DEBUG: [Mosquitto] prometheus.update
  2025-12-09T11:13:49+01:00 [PROMETHEUS] ERROR: Caught error
  2025-12-09T11:13:49+01:00 [PROMETHEUS] ERROR: Error: Added label "server" is not included in initial labelset: [
    'monitor_id',
    'monitor_name',
    'monitor_type',
    'monitor_url',
    'monitor_hostname',
    'monitor_port'
  ]
      at validateLabel (/home/user/Public/uptime-kuma/node_modules/prom-client/lib/validation.js:20:10)
      at set (/home/user/Public/uptime-kuma/node_modules/prom-client/lib/gauge.js:144:2)
      at Gauge.set (/home/user/Public/uptime-kuma/node_modules/prom-client/lib/gauge.js:29:3)
      at Prometheus.update (/home/user/Public/uptime-kuma/server/prometheus.js:157:31)
      at beat (/home/user/Public/uptime-kuma/server/model/monitor.js:965:30)
      at async safeBeat (/home/user/Public/uptime-kuma/server/model/monitor.js:992:17)
```

**Comment by CommanderStorm** [comment]
Looks resonable.
Could you do this as a PR instead, so you also get the credit?

**Comment by iotux** [comment]
@CommanderStorm, I am planning a PR for a feature request previously added (issue #1677, Monitor for Linux systemd services). 
I discovered the current issue during work with said monitor type, which I call "Local Service". The current issue #6470 is solved within the planned PR

**Comment by scosu** [comment]
I seem to have this exact same issue on version 2.2.1. I think this is not fixed? Could this bug be reopened please?

**Comment by edoswald** [comment]
Same bug here! Fixed in my fork by tracking which tags were known at startup (Prometheus.knownTagLabels), and skip any tag not in that set before it reaches prom-client's .set().

**Comment by FranciscoKnebel** [comment]
Having this error as well in my deployment, on 2.4.0. I use tagging a lot, so it's complaining non-stop for my monitors.

**Comment by LeonoreMangold** [comment]
+1

**Comment by christiaangoossens** [comment]
Issue is miscategorized as 'feature-request', while it is actually a bug. Even if the tags are ignored, they should not fill up my logs with errors.

**Comment by saiballo** [comment]
Confirmed on Uptime Kuma 2.5.5.
When a new monitor is created and a tag is assigned to it, the tag is not exposed in /metrics.
Restarting Uptime Kuma fixes it, but I also found that pausing and resuming the affected monitor is enough to make the tag appear in Prometheus metrics.
This seems to indicate that the Prometheus labels are refreshed when the monitor is restarted, but not when the monitor/tag is initially saved.
